version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped # nginx needs fpm runnning, and fpm needs nginx, so restart until both are ready
    ports:
      - "80:80"
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    restart: unless-stopped

