version: '2'
services:
  #fpm:
  #  image: php:fpm-alpine
  #  volumes:
  #    - ./dist:/usr/share/nginx/html
  #  ports:
  #    - "9000:9000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx-drivenow.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    #links:
    #  - fpm